In [10]:
import torch
x = torch.tensor([1, 2, 3])
y = torch.tensor([1, 2, 3])
mesh = torch.meshgrid(x, y, indexing='ij')
mesh


(tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]),
 tensor([[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]))

In [12]:
stack = torch.stack(mesh)
print(stack)
print(stack[1])

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


In [7]:
x = torch.randn(1,3)
print(x.shape)

torch.Size([1, 3])


In [8]:
x = torch.stack((x,x))
print(x.shape)

torch.Size([2, 1, 3])
