In [5]:
import torch

arr = torch.tensor([[1,2],[3,4]])
print(arr)

tensor([[1, 2],
        [3, 4]])


In [6]:
torch.sum(arr,dim=0)

tensor([4, 6])

In [8]:
import numpy as np

foo = np.array([[1,2],[3,4]])
np.sum(foo,axis=0)

array([4, 6])